// Every user-facing string in the app, organized by screen. Spanish
// groundwork: a translation is another file with the same shape. Strings
// that take values are small functions with named arguments (never
// concatenation at the call site), because word order changes across
// languages. Curated data content (candidate names, parties, race notes,
// state names, race titles) is data, not copy, and lives in ballot.js and
// the data files. No translation is done here and nothing is reworded:
// this file is behavior-neutral and invisible in the running app.
//
// Conventions: plain strings for fixed copy; `fn({ x })` for anything with
// a value in it; `pl(n, one, many)` picks a form for a count.

const pl = (n, one, many) => (n === 1 ? one : many);

export const strings = {
  ui: {
    // Coverage counts: DC is not a state, so 50 + DC reads "50 states and D.C."
    statesPhrase: ({ states, hasDC }) => `${states} ${states === 1 ? 'state' : 'states'}${hasDC ? ' and D.C.' : ''}`,
    tierCurated: 'Every scored position sourced',
    tierFec: 'Positions not stated yet',
    tierSample: 'Sample, not a real candidate',
    matchRingNotScoredA11y: 'Match not scored, not enough documented positions',
    matchRingPctA11y: ({ pct }) => `${pct} percent match with your answers`,
    matchRingDash: '-',
    matchRingPct: ({ pct }) => `${pct}%`,
    matchRingNotEnough: 'not enough info',
    matchRingMatch: 'match',
    progressA11y: ({ pct }) => `${pct} percent through the quiz`,
    back: 'Back',
    backTo: ({ label }) => `Back to ${label}`,
    backArrow: ({ label }) => `‹  ${label}`,
    pillFederal: 'Federal',
    pillLocal: 'Local',
    pillState: 'State',
    tabHome: 'Home',
    tabMatch: 'Match',
    tabBrowse: 'Browse',
    tabBallot: 'Ballot',
    tabHowTo: 'How to Vote',
    tabBallotHasMarks: 'Ballot, has marks',
  },

  districtLine: {
    changeA11y: 'Change your district',
    change: 'change',
    setDistrictLead: ({ name }) => `We don't know your district and we don't guess, so every ${name} House race we cover is here, in district order. `,
    setMyDistrict: 'Set my district',
    orLookItUpOn: ' or look it up on ',
    period: '.',
    redrawn: ({ name }) => ` District lines changed in ${name} for 2026, so a lookup based on who represents you today can be out of date.`,
  },

  rankedChoice: {
    title: 'Ranked choice race',
    ak: {
      siteLabel: 'Alaska Division of Elections',
      how: 'Alaska decides this race by ranked choice in the November 3 general election, after a top-four primary on August 18. Instead of picking one candidate, you rank them in the order you prefer, and you do not have to rank all of them.',
      safe: 'If your first choice is still in the count, your vote stays with them. Only if your first choice is eliminated does your vote move to your next choice.',
    },
    me: {
      siteLabel: 'Maine Secretary of State',
      how: 'Maine decides this race by ranked choice in the general election, as it does for federal offices. Instead of picking one candidate, you rank them in the order you prefer. Marking only a first choice is also valid.',
      safe: 'The count runs in rounds, and your ballot counts for your top remaining choice in every round. A later choice matters only if your earlier choices are eliminated.',
    },
    ballotNote: 'This sample ballot marks a single pick, while the real ballot asks for a ranking. Use your M2V pick as your first choice, and your match order for the rest.',
    linkA11y: ({ siteLabel }) => `How ranked choice works, from the ${siteLabel}, opens in your browser`,
    link: ({ siteLabel }) => `How it works, from the ${siteLabel} ↗`,
  },

  interest: {
    thanks: ({ name }) => `Thanks! We'll cover ${name} as soon as we can.`,
    buttonA11y: ({ name }) => `I want M2V to cover ${name}. Sends only your state, no email, no account`,
    button: ({ name }) => `I want M2V to cover ${name}`,
    note: 'Sends only your state. No email, no account, nothing else.',
  },

  home: {
    logoA11y: 'Match2Vote logo',
    title: 'Your 2026 Ballot',
    pickState: 'Pick your state to begin',
    stateAndDistrict: ({ state, district }) => `${state}, ${district}`,
    changeA11yState: 'Change your state or district',
    changeA11yNoState: 'Choose your state',
    change: '⌖ Change',
    countdownA11y: ({ days }) => `General Election, November 3, ${days} days away`,
    countdownLead: '▤ General Election · Nov 3 · ',
    countdownDays: ({ days }) => `${days} days away`,
    honestyBold: 'Every candidate here is real',
    honestyRest: ({ races, statesPhrase }) => `, rosters from official FEC filings, positions researched with a source for every score. We show only the ${races} races across ${statesPhrase} we've actually covered so far, and add more weekly.`,
    quizEyebrow: '✦ THE MATCH QUIZ',
    quizTitle: 'Answer 10 questions.\nMeet your candidates.',
    quizBody: "We'll rank the candidates we've researched by how well they line up with you, never by party.",
    quizStartA11y: 'Start the quiz',
    quizStart: 'Start the quiz  →',
    skipQuizA11y: 'Skip the quiz and fill out your ballot',
    skipQuiz: 'Done your own research? Skip the quiz and fill out your ballot',
    browseA11yState: ({ state }) => `Browse candidates, the races on your ${state} ballot`,
    browseA11y: 'Browse candidates, race by race',
    browseTitle: 'Browse candidates',
    browseBodyState: ({ state }) => `The races on your ${state} ballot, no quiz needed.`,
    browseBody: 'Race by race, no quiz needed.',
    howToA11y: 'How to vote, a 3-minute guide and your options',
    howToTitle: 'How to vote',
    howToBody: '3-min guide & your options.',
    rolesA11y: "What you're voting for: governor, senator, representative, what each job does",
    rolesTitle: "What you're voting for",
    rolesBody: 'Governor, senator, representative: what each job actually does.',
    racesHeader: "RACES WE'RE COVERING ON YOUR BALLOT",
    chosenCount: ({ chosen, total }) => `${chosen}/${total} chosen`,
    pickStateBody: "Pick your state to see the races we've researched for your ballot.",
    chooseMyState: 'Choose my state',
    notCovered: ({ state }) => `M2V doesn't cover ${state} yet.`,
    howToInYourState: 'How to vote in your state',
    raceA11yNamesOnly: 'names only, positions not researched yet',
    raceA11yVersus: ' versus ',
    raceA11y: ({ title, who, marked, pending }) => `Open ${title}, ${who}${marked ? ', marked on your ballot' : ', not marked yet'}${pending ? ', primary pending' : ''}`,
    namesOnly: 'Names only, positions not researched yet',
    vs: ' vs ',
    primaryDate: ({ date }) => `PRIMARY ${date}`,
    primaryPending: 'PRIMARY PENDING',
    aboutLink: 'How matching works & coverage',
    contactLink: 'Contact / report an error',
    linkArrow: ({ label }) => `${label}  ›`,
    footer: 'M2V is nonpartisan. Every scored position sourced. Never matched by party.',
  },

  browse: {
    title: 'Browse the races',
    intro: ({ races, statesPhrase }) => `${races} covered races across ${statesPhrase}, every position sourced, nothing guessed. Browsing here never changes your home state.`,
    stateA11y: ({ name, races }) => `${name}, ${races} ${pl(races, 'race', 'races')}`,
    stateRaces: ({ races }) => `${races} ${pl(races, 'race', 'races')}  ›`,
    dontSeeTitle: "Don't see your state?",
    dontSeeBody: "M2V doesn't cover it yet. We only show candidates whose positions we've researched and sourced, no placeholders, no guesses, and we're adding races weekly through Election Day.",
    allStates: 'All states',
    coveringHere: ({ full, names }) => `Races we're covering here: ${full} researched${names > 0 ? ` · ${names} names-only` : ''}`,
    raceA11yPendingSep: ', ',
    raceA11yVersus: ' versus ',
    raceA11y: ({ title, who, pending, namesOnly }) => `Open ${title}, ${who}${pending ? ', primary pending' : ''}${namesOnly ? ', names only' : ''}`,
    pendingSep: ' · ',
    vs: ' vs ',
    pendingRowNote: "Primary hasn't happened yet. These candidates are competing to be on the November ballot.",
    namesOnlyRowNote: "Names only, we haven't researched positions here yet.",
    notCovered: ({ state }) => `M2V doesn't cover ${state} yet.`,
    howToInYourState: 'How to vote in your state',
    primaryDate: ({ date }) => `PRIMARY ${date}`,
    primaryPending: 'PRIMARY PENDING',
    races: 'Races',
    raceMissing: "We don't cover this race yet, races are added weekly.",
    browseCovered: 'Browse covered races',
    raceDefaultNote: 'Candidates with researched, sourced positions.',
    pendingTitle: "Primary hasn't happened yet.",
    pendingBody: 'These candidates are competing to be on the November ballot; the field will change once the primary is decided.',
    redrawn: "District lines changed for 2026 in this state. If you knew your district number from a past election, confirm it on your state's official district finder before relying on this race.",
    namesOnlyTitle: "We know who's running here. We haven't researched their positions yet.",
    namesOnlyBody: "So there are no match percentages in this race. M2V never guesses a position from someone's party.",
    candA11yNominee: ', nominee',
    candA11yIncumbent: ', incumbent',
    candA11yNotScored: ', match not scored',
    candA11yPct: ({ pct }) => `, ${pct} percent match`,
    candA11y: ({ name, party, status, match }) => `Open ${name}, ${party}${status}${match}`,
    nominee: '  ·  Nominee',
    incumbent: '  ·  Incumbent',
    hidden: ({ n }) => `${n} other filed ${pl(n, 'candidate', 'candidates')} in this race${pl(n, " isn't", " aren't")} shown, positions not researched yet, and M2V never guesses.`,
    seeResults: 'See your results ›',
    takeQuiz: 'Take the quiz to see your match %',
    candidateMissing: "This candidate isn't in our researched set (yet).",
    profNominee: ' · Nominee',
    profIncumbent: ' · Incumbent',
    quote: ({ quote }) => `“${quote}”`,
    controversies: ({ n }) => `✳ ${n} reported ${pl(n, 'controversy', 'controversies')} on record`,
    controversyJoin: ': ',
    controversySourceA11y: ({ text }) => `Source for: ${text}`,
    controversySource: 'Source ›',
    fewPositions: 'We searched this candidate\'s website, surveys, and public records. They have published almost no positions, so most issues below show "Not stated." That\'s about their record, not our effort.',
    tileAge: 'AGE',
    tileHome: 'HOME',
    tileNow: 'NOW',
    background: 'Background',
    priorities: 'Top priorities',
    profNamesOnlyTitle: "We haven't researched this candidate's positions yet.",
    profNamesOnlyBody: 'No match percentage is shown, because M2V never guesses from party. This candidate is on the ballot per official filings.',
    positionSourceA11y: ({ issue, label }) => `Source for ${issue} position: ${label}`,
    positionSource: ({ label }) => `Source: ${label} ↗`,
    sourceButton: ({ label }) => `Source: ${label}`,
    marked: '✓ Marked on your ballot',
    mark: 'Mark on my ballot',
    markedA11y: ({ name }) => `Marked ${name} on your ballot, tap to see your ballot`,
    markA11y: ({ name, race }) => `Mark ${name} on my ballot for ${race}`,
    tapAgain: 'Tap again to see your ballot.',
  },

  ballot: {
    loading: 'Loading…',
    emptyTitle: 'YOUR SAMPLE BALLOT',
    electionLine: 'GENERAL ELECTION. TUESDAY, NOVEMBER 3, 2026',
    emptyBody: "This becomes your plan for election day. Browse your races, pick the candidates who actually agree with you, and walk in knowing exactly what you'll mark.",
    findMyRaces: 'Find my races',
    markedCount: ({ marked, total }) => `${marked} of ${total} races marked · tap an oval to mark`,
    primaryDate: ({ date }) => `PRIMARY ${date}`,
    primaryPending: 'PRIMARY PENDING',
    pendingNote: "Primary hasn't happened yet. These candidates are competing to be on the November ballot; this section will change.",
    pendingNoteMarked: ' Your mark is saved, but your pick may not reach November.',
    rowA11y: ({ name, party, pct, shared, total, researched, starred, filled, race }) =>
      `${name}, ${party}` +
      (researched && pct !== undefined && pct !== null ? `, ${pct} percent match on ${shared} of your ${total} issues` : '') +
      (!researched ? ', positions not researched' : '') +
      (starred ? ', your top match' : '') +
      (filled ? `, marked for ${race}, tap to unmark` : `, tap to mark for ${race}`),
    topMatch: '★ Your top match',
    matchLine: ({ pct, shared, total }) => ` · ${pct}% match on ${shared} of your ${total} issues`,
    notResearched: "We haven't researched this candidate's positions.",
    viewA11y: ({ name }) => `View ${name}'s positions`,
    view: 'view ›',
    starNote: '★ marks your top match in each race, based only on how your quiz answers line up with sourced positions. M2V does not endorse candidates. ',
    howMatchingWorks: 'How matching works\u00a0›',
    takeQuizNote: "Take the quiz and your match percentages will appear here next to the candidates we've researched.",
    share: 'Share my ballot as an image',
    shareSaved: 'Saved! Check your downloads.',
    shareShared: 'Shared.',
    shareFailed: 'Could not export on this device.',
    changeState: 'Change ballot state',
    bannerA11y: 'Sample ballot, not an official ballot, for planning only',
    bannerTitle: 'SAMPLE BALLOT: NOT AN OFFICIAL BALLOT',
    bannerSub: 'For planning only',
  },

  chooseState: {
    home: 'Home',
    title: 'Where do you vote?',
    intro: 'This sets which ballot you see. You can change it anytime from Home.',
    introUncovered: ' The few states with no 2026 statewide race are at the bottom.',
    rowA11y: ({ name, races }) => `${name}, ${races} ${pl(races, 'race', 'races')}`,
    rowA11yUncovered: ({ name }) => `${name}, no 2026 statewide race`,
    rowRaces: ({ races }) => `${races} ${pl(races, 'race', 'races')}`,
    rowNoRace: 'no 2026 race',
    footer: 'Every state gets the how-to-vote guide, including the ones with no statewide race this year.',
  },

  chooseDistrict: {
    home: 'Home',
    states: 'States',
    pickStateFirst: 'Pick your state first, then your district.',
    chooseMyStateA11y: 'Choose my state',
    chooseMyState: 'Choose my state  ›',
    title: 'Which district are you in?',
    intro: ({ name, seats }) => `${name} has ${seats} U.S. House districts. Pick yours below, or continue without one.`,
    knowTitle: 'I know my district',
    knowBody: 'Pick the number below.',
    unsureA11y: ({ name }) => `I'm not sure which district I'm in, continue without one and see every ${name} House race`,
    unsureTitle: "I'm not sure which district I'm in",
    unsureCta: 'Continue without one  ›',
    unsureNote: ({ name }) => `Not sure is fine. You'll see every House race in ${name} and can set your district later from your ballot.`,
    tileA11y: ({ label, current }) => `${label}${current ? ', your current district' : ''}`,
    atLarge: 'At-Large',
    districtN: ({ d }) => `District ${d}`,
    lookupLead: 'Not sure? Look it up on ',
    lookupTail: ', then pick the number here. We never see your address.',
    redrawn: ({ name }) => `District lines changed in ${name} for 2026, so a lookup based on who represents you today can be out of date.`,
  },

  howTo: {
    home: 'Home',
    title: 'How to vote',
    intro: "A 3-minute guide to your options. Rules vary by state, your state's official election site is always the final word. Match2Vote is an independent voter guide, not an official government or election-office app.",
    rolesA11y: "What you're voting for: the jobs on your ballot, explained",
    rolesLink: "New to this? What you're voting for: the jobs on your ballot, explained  ›",
    callout: "You don't need to be an expert to vote. Pick whichever way fits your life, by mail, early, or on the day. Your vote counts the same.",
    chapters: [
      { title: 'Before you go', body: 'Make sure you are registered, know where your polling place is, and bring an accepted photo ID just in case. Check your registration early, deadlines in many states fall weeks before Election Day.' },
      { title: 'Vote by mail', body: 'Request your ballot online or by form. When it arrives, mark it at home, seal it in the signed return envelope exactly as instructed, and return it by mail or at an official drop box before the deadline. You can usually track it online to confirm it was counted.' },
      { title: 'Vote early in person', body: 'Many areas open early-voting sites in the weeks before Election Day, often including evenings and weekends, and often any center in your area rather than one assigned place. Same ballot, usually shorter lines.' },
      { title: 'Vote on Election Day', body: 'Go to your assigned polling place during open hours and bring an accepted photo ID if your state requires one. If you make a mistake, ask a poll worker for a fresh ballot. If you are in line when polls close, stay in line, you can still vote.' },
      { title: 'Fill out your ballot', body: 'Vote every race you care about, follow the "vote for one" notes, and review your choices before you submit. Your M2V sample ballot is your plan. Bring it printed, or on your phone where your state allows phones in the voting booth, and copy your marks across.' },
    ],
    rules: {
      registrationDeadline: 'Registration deadline',
      sameDayRegistration: 'Same-day registration',
      yesAvailable: 'Yes, available',
      notAvailable: 'Not available',
      idRequirement: 'ID to bring',
      mailWho: 'Who can vote by mail',
      mailRequestBy: 'Request by',
      mailReturnBy: 'Return by',
      earlyStart: 'Early voting starts',
      earlyEnd: 'Early voting ends',
      note: 'Note',
      unconfirmed: 'We could not confirm this. Check the official site.',
      postmarkCounts: ' (postmark counts)',
      notAdded: ({ name }) => `We haven't added ${name}'s dates here yet. Your state's official election site is always the final word.`,
      rowLabel: ({ label }) => `${label}: `,
      officialSite: 'Official election site',
      officialSiteA11y: ({ label }) => `${label}, opens in your browser`,
      officialSiteLink: ({ label }) => `${label} ↗`,
      finalWord: 'The official site is always the final word. Rules can change; if you have been offline for a while, check it before relying on this.',
      checkedOn: ({ date }) => ` We checked this on ${date}.`,
      months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
      spokenDate: ({ month, day, year }) => `${month} ${day}, ${year}`,
    },
    planTitle: 'Walk in with a plan',
    planBody: "Mark your picks on your M2V sample ballot and bring it with you, it's the fastest way to vote confidently, top to bottom.",
    reviewA11y: 'Review my ballot',
    review: 'Review my ballot  →',
  },

  roles: {
    home: 'Home',
    title: "What you're voting for",
    intro: "The jobs on your ballot, in plain language. What each office can do, what it can't, and why it reaches you.",
    callout: 'This describes the offices, not the people running for them. Every line links to the official page it was checked against.',
    meansLead: 'What this means to you: ',
    whereFrom: 'Where this comes from',
    sourceA11y: ({ label }) => `${label}, opens in your browser`,
    sourceLink: ({ label }) => `${label} ↗`,
    nextTitle: "Now see who's running",
    nextBody: 'The races on your ballot, every position sourced.',
    browseA11y: 'Browse my races',
    browse: 'Browse my races  →',
    chapters: [
      {
        key: 'governor',
        title: 'Governor',
        lines: [
          'Runs the state\'s executive branch, the agencies that carry out state law.',
          'Signs bills into law or rejects them (a veto), and proposes the state budget the legislature then approves.',
          'Appoints most heads of state agencies, and in many states appoints judges. When the National Guard is not under federal control, the governor commands it.',
          'Clemency, the power to reduce or forgive a sentence, exists nearly everywhere but how it works varies by state.',
        ],
        means: 'The office closest to daily life. The budget the governor proposes, the bills they sign or veto, and the response when disaster hits all run through this desk.',
        sources: [
          { label: 'National Governors Association, Governors\' Powers & Authority' },
          { label: 'National Governors Association, Homeland Security' },
        ],
      },
      {
        key: 'senator',
        title: 'U.S. Senator',
        lines: [
          'Two per state, no matter how many people live there. Six-year terms, staggered so about a third of the Senate is on the ballot in any election.',
          'Writes and votes on federal bills. A bill has to pass both the House and the Senate before it reaches the President.',
          'Confirms or rejects the President\'s appointments, including federal judges and Cabinet secretaries, and approves or rejects treaties.',
          'A senator does not have a veto. The power to reject a bill (the veto) belongs to the President.',
        ],
        means: 'One of a hundred votes on national law, and on every federal judge who might one day hear your case.',
        sources: [
          { label: 'senate.gov, The Senate and the Constitution' },
          { label: 'senate.gov, Powers & Procedures' },
          { label: 'archives.gov, Constitution, Article I, Section 7' },
        ],
      },
      {
        key: 'representative',
        title: 'U.S. Representative',
        lines: [
          'One per district. Two-year terms, so all 435 seats are on the ballot in every federal election.',
          'Writes and votes on federal bills. Bills that raise money (taxes) must start in the House.',
          'The House decides whether to bring charges against a federal official (impeachment). The Senate then holds the trial.',
        ],
        means: 'The federal official closest to you, roughly 760,000 people each. Their office also handles casework: a stuck passport, a delayed VA claim, a Social Security question.',
        sources: [
          { label: 'house.gov, The House Explained' },
          { label: 'archives.gov, Constitution, Article I, Section 2' },
          { label: 'archives.gov, Constitution, Article I, Section 7' },
          { label: 'census.gov, 2020 Census apportionment' },
          { label: 'A House member\'s casework page (Rep. DelBene)' },
        ],
      },
      {
        key: 'delegate',
        title: 'Delegate (Washington, D.C.)',
        lines: [
          'Washington, D.C. does not have a voting representative. Instead it elects a delegate to the House.',
          'The delegate has the same powers as other members, with one exception: no vote when the full House is voting on the floor. That includes final passage of a bill.',
          'The delegate can introduce bills, sit on committees, and vote in committee.',
        ],
        means: 'A voice in the House for D.C. that can shape bills in committee but is not counted when the whole House votes. M2V covers this race.',
        sources: [
          { label: 'house.gov, The House Explained' },
          { label: 'house.gov, Directory of Representatives (Delegate seat)' },
        ],
      },
        ],
  },

  about: {
    title: 'About M2V',
    coverageTitle: 'Coverage right now',
    coverageBold: ({ races, candidates, statesPhrase }) => `${races} races · ${candidates} candidates · ${statesPhrase}`,
    coverageRest: "\nGrowing weekly through Election Day. We show only what we've actually researched, that's a feature, not an apology.",
    howTitle: 'How matching works',
    how1: 'You answer 10 questions. We compare your answers with what each candidate has publicly said or done, bills signed or vetoed, roll-call votes, lawsuits filed, statements on their own campaign site or in reputable coverage. Every scored position links to its source.',
    how2: 'We do not assign positions based on party. A candidate is scored on an issue only where we have a source documenting a relevant position; otherwise it stays "Not stated". Party labels are shown for identification only and play zero role in the math.',
    how3: "Your match percentage counts only the issues where you both weighed in. Issues you star count double. If there's not enough info for a fair number, we show a dash instead of a fake percentage.",
    how4: 'Why two percentages aren\'t always comparable: a candidate with fewer documented positions is scored on fewer of your issues. An 80% built on 6 issues is a thinner claim than a 60% built on all 10, the missing issues might be exactly where you\'d disagree. That\'s why every score shows its count ("across 8 of your 10 issues"), why we flag races where candidates have different counts, and why the "your top match" star is never given to a candidate who was scored on fewer issues than a rival. We refuse to fix this by guessing missing positions: unknown stays "Not stated," always.',
    how5: 'Candidate rosters come from official state candidate lists and FEC filings, refreshed nightly, plus hand-maintained governor races. Anything illustrative is labeled "Sample."',
    errorTitle: 'Spot an error?',
    errorBody: 'If a position or source looks wrong, tell us, we review it against the record and corrections go live within hours, no app update needed.',
    contact: 'Contact / report an error',
    appearance: 'Appearance',
    modeAutoA11y: 'Auto, follow the system appearance',
    modeLightA11y: 'Light appearance',
    modeDarkA11y: 'Dark appearance',
    modeAuto: 'Auto',
    modeLight: 'Light',
    modeDark: 'Dark',
    github: 'Open-source code & data (GitHub)',
    privacy: 'Privacy policy',
    nonpartisan: 'M2V is nonpartisan. It favors no party and no candidate.',
    org: 'Match2Vote is an independent, nonpartisan voter guide developed and published by Kiki Taylor, an independent developer based in Connecticut. It is not affiliated with any government agency, election office, party, or campaign.',
  },

  welcome: {
    eyebrow: 'WELCOME TO MATCH TO VOTE',
    title: 'Who actually\nagrees with you?',
    body: '10 quick questions. Candidates in covered November races. Every scored position has a source, never guessed from party.',
    stats: ({ races, statesPhrase }) => `${races} races · ${statesPhrase} · growing weekly`,
    start: 'Get started',
  },

  quiz: {
    strongly: 'Strongly',
    lean: 'Lean',
    middle: 'In the middle',
    answerA11y: ({ label, option, stance }) => `${label} toward option ${option}: ${stance}`,
    progress: ({ n, total, issue }) => `${n} of ${total} · ${issue} · progress saves automatically`,
    topIssueA11y: 'Make this a top issue, counts double in your match',
    topIssueOn: 'Top issue. Counts double in your match',
    topIssueOff: 'Make this a top issue',
    skipA11y: 'Skip this question',
    skip: 'Skip this one',
    previous: '‹ Previous question',
  },

  matches: {
    title: 'Your matches',
    notStartedBody: "Take the 10-question quiz and we'll show you who on your ballot actually agrees with you, with a source for every position.",
    startQuiz: 'Start the quiz (2 minutes)',
    resumeTitle: 'Pick up where you left off',
    resumeBody: ({ n, total }) => `You're ${n} of ${total} questions in, your answers are saved.`,
    resumeAt: ({ n }) => `Resume at question ${n}`,
    startOver: 'Start over instead',
    almostTitle: 'Almost there',
    almostBody: ({ n, total }) => `You answered ${n} of ${total} questions (skips don't count). We need at least 3 real answers to say anything meaningful about who agrees with you, a match built on less would be noise.`,
    answerMore: 'Answer more questions',
    oneMoreTitle: 'One more thing',
    oneMoreBody: "Tell us where you vote and we'll match you against your actual ballot.",
    chooseMyState: 'Choose my state',
    resultsTitle: "Here's who agrees with you",
    whereLine: ({ place }) => `${place} · November 3, 2026. `,
    stateAndDistrict: ({ state, district }) => `${state}, ${district}`,
    changeState: 'Change state',
    share: 'Share my matches (image)',
    shareSaved: 'Card saved! Post it anywhere.',
    shareShared: 'Shared.',
    shareFailed: 'Could not export here.',
    viewBallot: ({ marked, total }) => `View your ballot (${marked} of ${total} ${pl(total, 'race', 'races')} marked)`,
    openRaceA11y: ({ title }) => `Open the ${title} race`,
    raceTitle: ({ title }) => `${title} ›`,
    denominatorNote: ({ n }) => `These percentages cover different numbers of issues, because some candidates have fewer documented positions. They are not directly comparable, check the "of your ${n}" count under each name.`,
    openCandidateA11y: ({ name, party }) => `Open ${name}, ${party}, see positions`,
    seePositions: ({ first }) => `See ${first}'s positions ›`,
    sourced: ' · sourced ✓',
    pctLine: ({ pct, shared, total }) => `${pct}% across ${shared} of your ${total} ${pl(total, 'issue', 'issues')}`,
    notEnough: 'not enough documented positions to score',
    markedA11y: ({ name, race }) => `Marked ${name} on your ballot for ${race}, tap to unmark`,
    markA11y: ({ name, race }) => `Mark ${name} on your ballot for ${race}`,
    marked: '● Marked on your ballot · tap to unmark',
    mark: '◯ Mark on your ballot',
    retake: 'Retake the quiz',
    retakeConfirm: 'Retake the quiz? Your saved ballot stays exactly as it is, only your quiz answers reset.',
    retakeYes: 'Yes, retake',
    retakeNo: 'Never mind',
  },

  scenes: {
    vote: 'VOTE',
    house: 'HOUSE',
    senate: 'SENATE',
    committee: 'COMMITTEE',
    houseFloor: 'HOUSE FLOOR',
  },

  share: {
    matchesTitle: ({ stateName }) => `My top matches in ${stateName}, via M2V (Match to Vote)`,
    matchesRow: ({ n, name, pct, raceTitle }) => `${n}. ${name}${pct != null ? `, ${pct}% match` : ''} (${raceTitle})`,
    matchesTagline: ({ url }) => `Who actually agrees with YOU? ${url}`,
    matchesFooter: 'Every scored position sourced. Never matched by party.',
    cardBrand: 'M2V',
    cardBrandLong: 'MATCH TO VOTE',
    cardHeadline1: 'Here’s who actually',
    cardHeadline2: 'agrees with me',
    cardState: ({ stateName }) => `${stateName} · November 2026 ballot`,
    cardPct: ({ pct }) => `${pct}%`,
    cardDash: '-',
    cardRaceParty: ({ raceTitle, party }) => `${raceTitle}${party ? ` · ${party}` : ''}`,
    cardCta: 'Take the quiz, never matched by party:',
    ballotBanner: 'SAMPLE BALLOT: NOT AN OFFICIAL BALLOT. For planning only.',
    ballotHeader: ({ stateName }) => `${stateName.toUpperCase()} · GENERAL ELECTION. TUESDAY, NOVEMBER 3, 2026`,
    ballotRow: ({ title, picked }) => `${title.toUpperCase()}: ${picked ? `● ${picked.name} (${picked.party})` : '○ (not marked yet)'}`,
    ballotFooter: ({ url }) => `via M2V · ${url} · every position sourced`,
    ballotImgBanner: 'SAMPLE BALLOT: NOT AN OFFICIAL BALLOT',
    ballotImgSub: 'For planning only',
    ballotImgElection: 'GENERAL ELECTION. TUESDAY, NOVEMBER 3, 2026',
    ballotImgFooter: ({ url }) => `Marked with M2V · ${url} · every position sourced · never by party`,
  },

  crash: {
    detailsHeader: 'M2V crash details',
    detailsError: ({ message }) => `Error: ${message}`,
    detailsStack: ({ stack }) => `\nStack:\n${stack}`,
    detailsComponentStack: ({ componentStack }) => `\nComponent stack:${componentStack}`,
    unknownError: 'Unknown error',
    title: 'Something broke',
    body: 'Not your fault. Part of this screen hit an error it couldn\'t recover from. Your quiz answers, your state, and your ballot marks are saved on your device and are still there.',
    home: 'Back to Home',
    showDetails: 'Show technical details',
    hideDetails: 'Hide technical details',
    copy: 'Copy details',
    copied: 'Copied',
    copyFailed: 'Could not copy here',
    pasteNote: ({ contact }) => `You can paste this into an email to ${contact}. Nothing is sent unless you send it.`,
  },
};

export { pl };
